" Vim/Neovim Configuration File

" Disable Vi compatibility mode
set nocompatible

" Enable filetype detection, plugin, and indent functionality
filetype plugin indent on

" Set up fuzzy-finder (fzf)
if has('nvim')
  set rtp+=/opt/homebrew/opt/fzf
else
  set rtp+=~/.fzf
endif

" Enable syntax highlighting
syntax enable

" Disable the default Vim startup message
set shortmess+=I

" Show line numbers and relative line numbers
set number
set relativenumber

" Always show the status line
set laststatus=2

" Improve backspace behavior
set backspace=indent,eol,start

" Allow hidden buffers
set hidden

" Improve search behavior
set ignorecase
set smartcase
set incsearch
set hlsearch

" Clear search highlight with <ESC><ESC>
nnoremap <silent> <Esc><Esc> :nohlsearch<CR>

" Disable Ex mode
nnoremap Q <Nop>

" esc in insert & visual mode
inoremap jk <esc>
vnoremap jk <esc>

" esc in command mode
cnoremap jk <C-C>

" Disable audible bell
set noerrorbells visualbell t_vb=

" Enable mouse support
set mouse+=a

" Set indentation preferences
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent

" Change the location of .viminfo file (Neovim uses shada)
if has('nvim')
  set shada+=n~/.config/nvim/shada
else
  set viminfo+=n~/.config/vim/viminfo
endif

" Prevent bad movement habits
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
inoremap <Left>  <ESC>:echoe "Use h"<CR>
inoremap <Right> <ESC>:echoe "Use l"<CR>
inoremap <Up>    <ESC>:echoe "Use k"<CR>
inoremap <Down>  <ESC>:echoe "Use j"<CR>

" fzf shortcuts
nnoremap <silent> <C-f> :FZF<CR>

" CtrlP shortcuts
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

" Additional useful settings
set wildmenu
set wildmode=longest:full,full
set showcmd
set showmatch
set scrolloff=3
set sidescrolloff=5
set wrap
set linebreak
set formatoptions+=j
set ruler
set confirm
set history=1000
set undofile
if has('nvim')
  set undodir=~/.config/nvim/undodir
else
  set undodir=~/.config/vim/undodir
endif

" Plugin Manager (vim-plug)
if has('nvim')
  call plug#begin('~/.config/nvim/plugged')
else
  call plug#begin('~/.config/vim/plugged')
endif

Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'kyoz/purify', { 'rtp': 'vim' }
Plug 'christoomey/vim-tmux-navigator'

call plug#end()

" Set a color scheme
syntax on " This is required
colorscheme purify

if exists('+termguicolors')
  set termguicolors
endif

" Enable persistent undo
if has('persistent_undo')
  set undofile
  if has('nvim')
    set undodir=~/.config/nvim/undo
  else
    set undodir=~/.vim/undo
  endif
endif

" Highlight current line
set cursorline

" Enable folding
set foldmethod=indent
set foldlevel=99

" Remap leader key
let mapleader = ","

" Quick save
nnoremap <leader>w :w<CR>

" Split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Buffer navigation
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bprevious<CR>

" Set updatetime for faster git-gutter updates
set updatetime=100" Make the cursor bold
set guicursor=n-v-c-sm:block-blinkwait50-blinkon50-blinkoff50,i-ci-ve:ver25-blinkwait50-blinkon50-blinkoff50,r-cr-o:hor20-blinkwait50-blinkon50-blinkoff50,a:blinkon50-blinkwait50-blinkoff50