" Vim Configuration File

" Disable Vi compatibility mode
set nocompatible

" Enable filetype detection, plugin, and indent functionality
filetype plugin indent on

" Set up fuzzy-finder
set rtp+=/opt/homebrew/opt/fzf

" Enable syntax highlighting
syntax enable

" Disable the default Vim startup message
set shortmess+=I

" Show line numbers and relative line numbers
set number
set relativenumber

" Always show the status line
set laststatus=2

" Improve backspace behavior
set backspace=indent,eol,start

" Allow hidden buffers
set hidden

" Improve search behavior
set ignorecase
set smartcase
set incsearch
set hlsearch

" Disable Ex mode
nnoremap Q <Nop>

" Disable audible bell
set noerrorbells visualbell t_vb=

" Enable mouse support
set mouse+=a

" Set indentation preferences
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent

" Change the location of .viminfo file
set viminfo+=n~/.config/vim/viminfo

" Prevent bad movement habits
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
inoremap <Left>  <ESC>:echoe "Use h"<CR>
inoremap <Right> <ESC>:echoe "Use l"<CR>
inoremap <Up>    <ESC>:echoe "Use k"<CR>
inoremap <Down>  <ESC>:echoe "Use j"<CR>

" fzf shortcuts
nnoremap <silent> <C-f> :FZF<CR>

" CtrlP shortcuts
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

" Additional useful settings
set wildmenu
set wildmode=longest:full,full
set showcmd
set showmatch
set scrolloff=3
set sidescrolloff=5
set wrap
set linebreak
set formatoptions+=j
set ruler
set confirm
set history=1000
set undofile
set undodir=~/.config/vim/undodir

" Plugin Manager
call plug#begin('~/.config/vim/plugged')
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'whatyouhide/vim-gotham'
call plug#end()

" Set a color scheme
colorscheme gotham

if exists('+termguicolors')
    set termguicolors
endif

" Enable persistent undo
if has('persistent_undo')
    set undofile
    set undodir=~/.vim/undo
endif

" Highlight current line
set cursorline

" Enable folding
set foldmethod=indent
set foldlevel=99

" Remap leader key
let mapleader = ","

" Quick save
nnoremap <leader>w :w<CR>

" Split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Set updatetime for faster git-gutter updates
set updatetime=100
